// generated by stringer -type=Item -output=token_string.go; DO NOT EDIT

package tl

import "fmt"

const _Item_name = "ItemIllegalItemWhitespaceItemEOFItemUnderscoreItemColonItemSemicolonItemOpenParItemCloseParItemOpenBracketItemCloseBracketItemOpenBraceItemCloseBraceItemLeftAngleItemRightAngleItemTripleMinusItemEqualsItemHashItemExclMarkItemQuestionMarkItemPercentItemPlusItemCommaItemDotItemAsteriskItemNatConstItemLowerIdentItemUpperIdentItemFinalItemNewItemEmpty"

var _Item_index = [...]uint16{0, 11, 25, 32, 46, 55, 68, 79, 91, 106, 122, 135, 149, 162, 176, 191, 201, 209, 221, 237, 248, 256, 265, 272, 284, 296, 310, 324, 333, 340, 349}

func (i Item) String() string {
	if i < 0 || i+1 >= Item(len(_Item_index)) {
		return fmt.Sprintf("Item(%d)", i)
	}
	return _Item_name[_Item_index[i]:_Item_index[i+1]]
}
